baseURL = "https://edgarnegron.dev/"
languageCode = "en-us"
title = "Edgar Negrón's Portfolio"
assetDir = "static/assets"


[params]
    headerTitle = "Edgar Negrón Rabell"



[module]
	[hugoVersion]
	extended = true
