baseURL = "https://edgarnegronrabell.dev/"
languageCode = "en-us"
title = "Edgar Negrón's Portfolio"
assetDir = "static/assets"


[params]
    headerTitle = "Edgar Negrón Rabell"

    projectsLabel = "Projects"
    projectsLink = "/projects"

    blogLabel = "Blog"
    bloglink = "/blog"

    aboutLabel = "About"
    aboutlink = "/about"

    contactMeLabel = "Contact Me"
    contactMelink = "/contact-me"



[module]
	[hugoVersion]
	extended = true
